/**
 * AI-Generated Demo Recording
 *
 * 시나리오: 인하우스 번역가가 클라우드 보안 정책 문서를 한→영 번역
 * 타겟 페르소나: IT 기업 인하우스 번역가 (기술 문서 담당)
 * 강조 포인트: 듀얼 에디터 + 원클릭 번역의 효율성
 *
 * Generated by /record-demo skill
 */

import { test, type Page } from '@playwright/test';
import { injectTauriMock } from './tauri-mock';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const RECORDINGS_DIR = path.resolve(__dirname, '../remotion-demo/public/recordings');

// ── Timing Constants ──
const TYPE_DELAY = 35;
const STEP_PAUSE = 800;
const EMPHASIS_PAUSE = 1500;

// ── Helpers ──
async function renameVideo(page: Page, targetName: string): Promise<void> {
  const video = page.video();
  if (!video) return;
  const videoPath = await video.path();
  if (!videoPath) return;
  fs.mkdirSync(RECORDINGS_DIR, { recursive: true });
  const dest = path.join(RECORDINGS_DIR, targetName);
  fs.copyFileSync(videoPath, dest);
  console.log(`[record-ai] Saved: ${dest}`);
}

// ── AI Generated Scenario ──
test.describe.serial('AI Demo Recording', () => {
  test('번역 데모 — 클라우드 보안 정책 한→영', async ({ page }) => {
    // 1. Mock 주입 (빈 상태 — 프로젝트 생성부터 시작)
    await injectTauriMock(page);
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(STEP_PAUSE);

    // 2. 새 프로젝트 생성
    await page.getByRole('button', { name: '새 프로젝트 시작하기' }).click();
    await page.waitForTimeout(STEP_PAUSE);

    // 3. Source 에디터에 기술 문서 입력
    const sourceEditor = page.locator('[contenteditable="true"]').first();
    await sourceEditor.click();
    await page.waitForTimeout(300);

    // 제목
    await page.keyboard.type('클라우드 보안 정책 가이드', { delay: TYPE_DELAY });
    await page.keyboard.press('Enter');
    await page.keyboard.press('Enter');

    // 본문 1단락
    await page.keyboard.type(
      '본 문서는 클라우드 환경에서의 데이터 보호 및 접근 제어에 관한 정책을 정의합니다. 모든 부서는 아래 가이드라인을 준수해야 합니다.',
      { delay: TYPE_DELAY },
    );
    await page.keyboard.press('Enter');
    await page.keyboard.press('Enter');

    // 소제목 + 본문 2단락
    await page.keyboard.type('데이터 분류 및 보호', { delay: TYPE_DELAY });
    await page.keyboard.press('Enter');
    await page.keyboard.type(
      '기밀 데이터는 AES-256 암호화를 적용하며, 전송 시 TLS 1.3 이상을 사용합니다. 개인식별정보(PII)는 별도의 암호화된 스토리지에 저장하고, 접근 로그를 90일간 보관합니다.',
      { delay: TYPE_DELAY },
    );
    await page.keyboard.press('Enter');
    await page.keyboard.press('Enter');

    // 소제목 + 본문 3단락
    await page.keyboard.type('접근 제어 정책', { delay: TYPE_DELAY });
    await page.keyboard.press('Enter');
    await page.keyboard.type(
      '최소 권한 원칙(Principle of Least Privilege)을 적용합니다. 관리자 계정은 MFA를 필수로 설정하며, 90일마다 비밀번호를 갱신합니다.',
      { delay: TYPE_DELAY },
    );

    // 문서 입력 완료 — 듀얼 에디터 전체 모습 강조
    await page.waitForTimeout(EMPHASIS_PAUSE);

    // 4. 타겟 언어 선택 (영어)
    const langSelect = page
      .getByRole('button', { name: /^(언어 선택|Select Language)$/ })
      .first();
    await langSelect.click();
    await page.waitForTimeout(STEP_PAUSE);

    await page.getByRole('option', { name: /^(영어|English)$/ }).click();
    await page.waitForTimeout(STEP_PAUSE);

    // 5. 번역 버튼 클릭 — 핵심 순간
    await page.getByRole('button', { name: /^(번역|Translate)$/ }).click();
    await page.waitForTimeout(EMPHASIS_PAUSE);

    // 6. 번역 결과 대기 (mock이므로 즉시 완료, 결과 화면 유지)
    await page.waitForTimeout(EMPHASIS_PAUSE);

    // 7. 최종 듀얼 에디터 모습 — Source/Target 나란히 보여주기
    await page.waitForTimeout(2000);

    // 8. 비디오 저장
    await renameVideo(page, 'Translate_AI.webm');
  });
});
